version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    # Для продакшен-сервера отключаем публичный доступ к порту базы данных
    # ports:
    #   - "3306:3306"
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://${DOMAIN_NAME}');
        define('WP_SITEURL', 'https://${DOMAIN_NAME}');
        define('FORCE_SSL_ADMIN', true);
        $_SERVER['HTTPS'] = 'on';
        
        # Дополнительные настройки безопасности
        define('DISALLOW_FILE_EDIT', true);
        define('AUTOMATIC_UPDATER_DISABLED', false);
        define('WP_AUTO_UPDATE_CORE', 'minor');
        
        # Принудительный HTTPS для всего сайта
        if (strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
            $_SERVER['HTTPS'] = 'on';
        }
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content/themes/aviator-theme:/var/www/html/wp-content/themes/aviator-theme
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - wordpress_network

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    depends_on:
      - wordpress
    ports:
      # Используем нестандартный порт 8080 для HTTP
      - "8080:80"
      # HTTPS порт для основного доступа
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-1xbet-install.com}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./logs/caddy:/var/log/caddy
    networks:
      - wordpress_network

  # Изменяем wp-cli для однократного запуска без перезапуска
  wp-cli:
    image: wordpress:cli
    container_name: wp-cli
    # Меняем на "no" чтобы избежать цикла перезапуска
    restart: "no"
    # Ждем пока WordPress полностью настроится
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content/themes/aviator-theme:/var/www/html/wp-content/themes/aviator-theme
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - wordpress_network
    command: >
      /bin/sh -c '
      # Ждем пока база данных и WordPress будут готовы
      echo "Ожидание 30 секунд для инициализации WordPress..."
      sleep 30
      
      # Исправление прав доступа
      echo "Настройка прав доступа..."
      mkdir -p /var/www/html/wp-content/upgrade
      chmod -R 755 /var/www/html/wp-content
      
      # Установка WordPress
      echo "Настройка WordPress..."
      wp core install --path="/var/www/html" --url="https://${DOMAIN_NAME}" --title="Aviator Game Site" --admin_user=admin --admin_password=admin --admin_email=admin@example.com --skip-email || true
      
      # Настройка темы и плагинов
      echo "Активация темы..."
      wp theme activate aviator-theme --path="/var/www/html" || true
      
      echo "Установка плагинов..."
      wp plugin install wordpress-importer --activate --path="/var/www/html" || true
      wp plugin install wordfence --activate --path="/var/www/html" || true
      
      echo "Настройка параметров сайта..."
      wp option update blogname "1xBet Aviator" --path="/var/www/html" || true
      wp option update blogdescription "Aviator Game - A Simple and Exciting Game" --path="/var/www/html" || true
      wp option update permalink_structure "/%postname%/" --path="/var/www/html" || true
      
      echo "Настройка WordPress завершена"
      '

networks:
  wordpress_network:

volumes:
  db_data:
  wordpress_data:
  caddy_data:
  caddy_config:
